M48
; DRILL file {KiCad (6.0.0)} date Mon May 16 20:33:28 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-16T20:33:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0906
%
G90
G05
T1
X7.1726Y-3.2591
X7.2126Y-2.9591
X7.2526Y-3.2591
T2
X6.9035Y-2.9398
X6.9035Y-3.2154
T3
X7.0331Y-4.6457
T0
M30
